### ISSUE TITLE
Widgets->Calendar crash when click.

### ISSUE THREAD

**Issue by hongnod** [copperspice/kitchensink#1]
Run on Windows10 64bit, when click Widgets->Calendar, KS will crash.

**Comment by agserm** [comment]
We have tried this in our Windows 10 64-bit test environment and have not been able to reproduce the issue. We will continue working on reproducing this behavior. If there is any more information you can provide about the crash that might help us narrow down what is happening, please let us know.

Thanks for testing and reporting this!

**Comment by hongnod** [comment]
Tried on another computer, crashed again. I use the version download from : http://download.copperspice.com/kitchensink/binary/setup-KitchenSink-1.4.0-x64.exe

**Comment by agserm** [comment]
We have still not been able to reproduce this issue. We have tested this exact download on windows 7 and windows 10. Trying to figure out what might be different about your system configuration which is causing the crash. 

- What locale and time zone is your computer set to? 
- Does it crash immediately as soon as you click on the menu item?
- Does anything display on the screen from the calendar or does it crash before anything is drawn?

Thanks for any additional information.

**Comment by hongnod** [comment]
locale: China ; time zone: GMT+8
crash immediately
crash before anything is drawn

**Comment by agserm** [comment]
With your additional information, we have been able to reproduce the problem by simply opening the calendar and changing the locale from English/UnitedStates to Chinese/China.

If you want to verify this, you can change your system locale to English/UnitedStates and you will be able to open the Calendar window. We are working on resolving this issue, and it seems to affect other locales as well such as Russia.

Thanks for your help!

**Comment by hongnod** [comment]
You are welcome.

**Comment by agserm** [comment]
We have traced this crash to an issue in the integration with the harfbuzz unicode text shaping library in CopperSpice. We are in the process of updating to a newer version of harfbuzz, as there are several known issues in this area. When we integrate the updated version of harfbuzz we will retest this issue. This should occur over the next few weeks.

**Comment by hongnod** [comment]
good to know the news! congratulations.

**Comment by agserm** [comment]
This issue is resolved in https://github.com/copperspice/copperspice/commit/ee441106658d6351af5b2d6e0a4c9d48daa825ac. Thank you for the report!
