### ISSUE TITLE
Segfault when close Table Widget / View

### ISSUE THREAD

**Issue by stefanos82** [copperspice/kitchensink#5]
Good evening and happy new year.

I have noticed a segfault via terminal when I close Table Widget / View window.

It can be reproduced as follows:

- Open kitchensink via terminal and open Table Widget / View
- Press on multiple cells to produce multiple popup windows
- Close the last opened popup window; you should not see any other popup window in front of you
- Close the Table Widget / View window
- Exit kitchensink; on top of your terminal you should see the remaining popup windows
- close one by one and on the last one you will see a segfault

I have tried to backtrace it via GDB but did not provide any actual information for some reason :thinking: 

I'm using GNU / Linux Debian testing 64-bit fully updated with the latest copperspice and kitchensink master repositories with `gcc (Debian 10.2.1-3) 10.2.1 20201224`

**Comment by agserm** [comment]
Thanks for reporting this! Commit b11234f resolves this issue.
